vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /media/products
            upload_destination: '%kernel.project_dir%/public/media/products'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
